" vimrc file

" When started as "evim", evim.vim will already have done these settings, bail
" out.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

" Configure directories for backups
set undofile
set backup
let &directory = expand('~/.cache/vim/swap//')
let &backupdir = expand('~/.cache/vim/backup//')
let &undodir   = expand('~/.cache/vim/undo//')

" Create directories and set their permissions
if !isdirectory(&directory) | call mkdir(&directory, "p", "0700") | endif
if !isdirectory(&backupdir) | call mkdir(&backupdir, "p", "0700") | endif
if !isdirectory(&undodir)   | call mkdir(&undodir, "p", "0700")   | endif

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Text width settings
hi clear ColorColumn
hi ColorColumn ctermbg=237 guibg=Grey23
augroup vimrcEx
	au!
	autocmd FileType text     setlocal textwidth=100 colorcolumn=100
	autocmd FileType markdown setlocal textwidth=100 colorcolumn=100
augroup END

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif

" Editor settings:
set tabstop=3
set shiftwidth=0
"set expandtab
set number
set nowrap
set scrolloff=5

" Vertical Split
hi clear VertSplit
hi VertSplit ctermbg=232 ctermfg=245 guibg=Grey3 guifg=Grey54
set fillchars+=vert:\│

" Statusline:
hi clear StatusLine
hi clear StatusLineNC
hi StatusLine   term=bold cterm=bold gui=bold ctermbg=234 guibg=Grey11
hi StatusMode   term=bold cterm=bold gui=bold ctermfg=234 guifg=Grey11 ctermbg=34 guibg=Green3
hi StatusLineNC ctermbg=232 guibg=Grey3
if $USER == 'root' | hi Statusline ctermfg=124 | else | hi Statusline ctermfg=15 | endif
set laststatus=2

let g:currentmode={
	\ 'n' : 'NORMAL',
	\ 'v' : 'VISUAL',
	\ 'V' : 'V-LINE',
	\ '': 'V-BLOCK',
	\ 's' : 'SELECT',
	\ 'S' : 'S-LINE',
	\ '': 'S-BLOCK',
	\ 'i' : 'INSERT',
	\ 'R' : 'REPLACE',
	\ 'Rv': 'V-REPLACE',
	\ 'c' : 'COMMAND',
	\ 't' : 'TERMINAL',
	\}

function! PrepInfo()
	let l:full_info = ""
	if strlen(&filetype) > 0     | let l:full_info = l:full_info . &filetype . "|"     | endif
	if strlen(&fileencoding) > 0 | let l:full_info = l:full_info . &fileencoding . "|" | endif
	if strlen(&ff) > 0           | let l:full_info = l:full_info . &ff                 | endif
	return l:full_info
endfunction

" Dinamically set the statusline based on active/inactive split.
augroup statusline
	autocmd!
	autocmd WinEnter,BufEnter * setlocal statusline=%#StatusMode#\ %{g:currentmode[mode()]}\ %#StatusLine#\ %t\ %M%=%r\ %l:%c/%L\ %{PrepInfo()}\ %p%%\ 
	autocmd WinLeave,BufLeave * setlocal statusline=%#StatusLineNC#\ %t\ %M%=%R\ %L\ %p%%\ 
augroup end

" The custom statusline shows the current mode, hide it from command line to
" avoid redundancy.
set noshowmode

" Use system clipboard
set clipboard+=unnamedplus

" Cursor line:
hi clear CursorLine
hi clear CursorLineNr
hi CursorLine   ctermbg=233 guibg=Grey7
hi CursorLineNr ctermbg=233 guibg=Grey7 ctermfg=11 gui=bold guifg=Yellow
set cursorline

" Folds
hi clear Folded
hi Folded ctermfg=13 ctermbg=235 guifg=Fuchsia guibg=Grey15
set fillchars+=fold:═

" Tabline
hi clear TabLine
hi clear TabLineFill
hi clear TabLineSel
hi TabLine ctermfg=15 ctermbg=232 guifg=White guibg=Grey3
hi TabLineFill ctermfg=0 ctermbg=232 guibg=Grey3
hi TabLineSel cterm=bold ctermfg=15 ctermbg=234 guibg=Grey11
